<?php

    return [
        "appkey"=>"B01B3FFD-A4B0-4891-9887-4E71E1AE4265",
        "delivery"=>[
            "deliveryType"=>[
                "type"=>"auto"
            ],
            "arrival"=>[
                "time"=>[
                "worktimeStart"=>"9:30",
                "worktimeEnd"=>"19:00",
                "breakStart"=>"12:00",
                "breakEnd"=>"13:00",
                "exactTime"=>false
                ]
            ],
            "derival"=>[
                "time"=>[
                "worktimeEnd"=>"19:30",
                "worktimeStart"=>"9:00",
                "breakStart"=>"12:00",
                "breakEnd"=>"13:00",
                "exactTime"=>false
                ]
            ],
            "packages"=>[
                [
                "uid"=>"0xAE2EEA993230333043E719D4965D5D31",
                "count"=>1
                ]
            ],
            "accompanyingDocuments"=>[
                [
                "action"=>"send"
                ],
                [
                "action"=>"return"
                ]
            ]
        ],
        "members"=>[
            "requester"=>[
                "role"=>"sender"
            ]
        ],
        "cargo"=>[
            "quantity"=>1,
            "length"=>1,
            "width"=>1,
            "height"=>1,
            "hazardClass"=>0
        ]
    ];